// generated by tscfg 0.8.0 on Mon Feb 06 19:14:52 CET 2017
// source: config.conf

package de.awilhelmer.alexaskill.mqtt.config;

public class Config {
   public final Mqtt_skill mqtt_skill;

   public static class Mqtt_skill {
      public final Commands commands;
      public final Devices devices;
      public final Mqtt_host mqtt_host;

      public static class Commands {
         public final java.util.List<List$Elm> list;

         public static class List$Elm {
            public final String command;
            public final String mqtt_command;
            public final String type;
            public final boolean value;

            public List$Elm(com.typesafe.config.Config c) {
               this.command = c.hasPathOrNull("command") ? c.getString("command") : null;
               this.mqtt_command = c.hasPathOrNull("mqtt-command") ? c.getString("mqtt-command") : null;
               this.type = c.hasPathOrNull("type") ? c.getString("type") : null;
               this.value = c.hasPathOrNull("value") && c.getBoolean("value");
            }
         }

         public Commands(com.typesafe.config.Config c) {
            this.list = $_LCommands_List$Elm(c.getList("list"));
         }

         private static java.util.List<List$Elm> $_LCommands_List$Elm(com.typesafe.config.ConfigList cl) {
            java.util.ArrayList<List$Elm> al = new java.util.ArrayList<>();
            for (com.typesafe.config.ConfigValue cv : cl) {
               al.add(new List$Elm(((com.typesafe.config.ConfigObject) cv).toConfig()));
            }
            return java.util.Collections.unmodifiableList(al);
         }
      }

      public static class Devices {
         public final java.util.List<List$Elm2> list;

         public static class List$Elm2 {
            public final String name;
            public final String topic;
            public final String type;

            public List$Elm2(com.typesafe.config.Config c) {
               this.name = c.hasPathOrNull("name") ? c.getString("name") : null;
               this.topic = c.hasPathOrNull("topic") ? c.getString("topic") : null;
               this.type = c.hasPathOrNull("type") ? c.getString("type") : null;
            }
         }

         public Devices(com.typesafe.config.Config c) {
            this.list = $_LDevices_List$Elm2(c.getList("list"));
         }

         private static java.util.List<List$Elm2> $_LDevices_List$Elm2(com.typesafe.config.ConfigList cl) {
            java.util.ArrayList<List$Elm2> al = new java.util.ArrayList<>();
            for (com.typesafe.config.ConfigValue cv : cl) {
               al.add(new List$Elm2(((com.typesafe.config.ConfigObject) cv).toConfig()));
            }
            return java.util.Collections.unmodifiableList(al);
         }
      }

      public static class Mqtt_host {
         public final String hostname;
         public final String password;
         public final String username;

         public Mqtt_host(com.typesafe.config.Config c) {
            this.hostname = c.hasPathOrNull("hostname") ? c.getString("hostname") : null;
            this.password = c.hasPathOrNull("password") ? c.getString("password") : null;
            this.username = c.hasPathOrNull("username") ? c.getString("username") : null;
         }
      }


      public Mqtt_skill(com.typesafe.config.Config c) {
         this.commands = new Commands(c.getConfig("commands"));
         this.devices = new Devices(c.getConfig("devices"));
         this.mqtt_host = new Mqtt_host(c.getConfig("mqtt-host"));
      }
   }

   public Config(com.typesafe.config.Config c) {
      this.mqtt_skill = new Mqtt_skill(c.getConfig("mqtt-skill"));
   }
}
      
